### ISSUE TITLE
Namespace issue in Firefox and Internet Explorer

### ISSUE THREAD

**Issue by johu2** [toastedlime/wp-attachment-importer#1]
I got fallowing error. If you need some info about the xml, I used, ask for the fields. I don't want to upload the whole file.

could not be uploaded because of an error. (upload_dir_error: Empty filename)

WP version  Version 3.8.1 
Importer Stable tag: 0.5.3

**Comment by johu2** [comment]
It seems that xml parses with no results although there are items with 

```
  <wp:post_type>attachment</wp:post_type>
```

in the XML.

Update:
It seems the parser can not find them due to namespace wp. Googling my way out of it right now.

**Comment by piontkowski** [comment]
Hello. Did you find a solution? If not, can you share the first `<item></item>` that caused the error?

**Comment by johu2** [comment]
Well I learnt a lot of javascript today, but did not solve it fully. The namespace is the issue. The line 

``` javascript
var xml_post_type = $( this ).find( 'post_type' ).text();
```

did not match any nodes. If I replace  'post_type' with something without namespace it works. It does not work with 'wp:post_type'. I guess the xml format has recently changed as there are many other fields the current parser probably would also not find.

Here is a example of XML exported from wordpress.com

``` xml
<item>
  <title>UniZ peahoone</title>
  <link>http://n2lgzurichis.wordpress.com/2012/09/11/vasinud-jalad/20120911_113548/</link>
  <pubDate>Tue, 11 Sep 2012 19:36:34 +0000</pubDate>
  <dc:creator>johu002</dc:creator>
  <guid isPermaLink="false">http://n2lgzurichis.files.wordpress.com/2012/09/20120911_113548.jpg</guid>
  <description/>
  <content:encoded><![CDATA[]]></content:encoded>
  <excerpt:encoded><![CDATA[]]></excerpt:encoded>
  <wp:post_id>13</wp:post_id>
  <wp:post_date>2012-09-11 19:36:34</wp:post_date>
  <wp:post_date_gmt>2012-09-11 19:36:34</wp:post_date_gmt>
  <wp:comment_status>open</wp:comment_status>
  <wp:ping_status>open</wp:ping_status>
  <wp:post_name>20120911_113548</wp:post_name>
  <wp:status>inherit</wp:status>
  <wp:post_parent>10</wp:post_parent>
  <wp:menu_order>0</wp:menu_order>
  <wp:post_type>attachment</wp:post_type>
  <wp:post_password/>
  <wp:is_sticky>0</wp:is_sticky>
  <wp:attachment_url>http://n2lgzurichis.files.wordpress.com/2012/09/20120911_113548.jpg</wp:attachment_url>
</item>
```

You might be a javascript pro, but I did not understand, how `$( this ).find` works. Maybe you could point me to a reference. I only found <a href=http://www.w3schools.com/dom/dom_element.asp>references</a> recommending `getElementsByTagName()` and `getElementsByTagNameNS()`, which supports namespace. This should work, but I did not have time to rewrite the parsing of different fields this far. If you should do that I would be happy to have the patch or .js file.

**Comment by piontkowski** [comment]
I was not able to replicate the issue. Using your sample data above, I was able to import the image to a test server. Was this the first image that caused the error? The program tries to import the attachments in the order they appear in the XML file.  Also, what browser and version of that browser are you using?

Also, for `$(this)` I like this article: http://remysharp.com/2007/04/12/jquerys-this-demystified/.

**Comment by johu2** [comment]
Ok. Thanks for the reference. I am familiar with OOP and I do no about `this`. but not `$(this)`. I also have to learn about the 'find' function. As I don't know what kind of object you get from `$(this)`, I can't find any corresponding documentation.

The order of items should not matter. I could send you the full xml file to your personal email later, but I guess as long as it parses the namespaces for you, it would be of no help.

From additional debugging output I am positive, that `xml_post_type` was always zero length string for all items in the list. This results the url and other lists to be of 0 length and the error message I quoted above printed by .done routine ajax call.

<a href=http://pastebin.com/be4kkXzm>Troubleshooting information</a> of my browser.

**Comment by piontkowski** [comment]
Thanks for pointing me towards the namespace issue. I was using Chrome. FF needs the namespace specified. Can you download the master branch and try your upload again?

Ref: http://stackoverflow.com/questions/10181087/xml-findsomeelement-pulling-values-with-jquery-from-xml-with-namespace

**Comment by johu2** [comment]
I confirm. Works. Thanks!
