### ISSUE TITLE
Invalid file type should produce non-fatal error

### ISSUE THREAD

**Issue by drrobotnik** [toastedlime/wp-attachment-importer#11]
On an import it died in the middle because the client had uploaded a JS file into the media library. Update: Actually it was dying on the SWF file.

![Shame shame...](http://caava-clients.s3-us-west-1.amazonaws.com/Screen%20Shot%202014-03-20%20at%201.02.42%20PM.png)

![Culprit](http://caava-clients.s3-us-west-1.amazonaws.com/Screen%20Shot%202014-03-20%20at%201.05.05%20PM.png)

I can remove the file in the WXR and re-run, but I think most people would expect the importer to make note of the invalid file type and skip it. Especially with the set it and forget it until tomorrow nature of the import.

I think this is where the issue is:
https://github.com/toastedlime/wp-attachment-importer/blob/master/index.php#L170

**Comment by piontkowski** [comment]
I think that's fair. When the program encounters an invalid file type, the error should not be fatal.

**Comment by piontkowski** [comment]
Closed in 0.5.6
