### ISSUE TITLE
Improved loging

### ISSUE THREAD

**Issue by johu2** [toastedlime/wp-attachment-importer#3]
I just uploaded successfully 4000 items. In general it worked nicely, but few features could improve it.
- Few random files failed on each run due to 'server did not respond'. I optimised the XML by hand for the new run, but it would be cool, if I got copy with failed elements from the plugin for a new run. Running the whole XML again takes a lot of time.
- Output log in single div or even ul elements such that the log would not be so long because of large spacing.
- Progress bar in top or at least done/total numbers in the log to indicate the progress.

**Comment by piontkowski** [comment]
Thanks for your suggestions! I opened a couple as separate tickets. Feel free to fork and dive in if you have some time!
