### ISSUE TITLE
Random files fail with "Remote server did not respond" error

### ISSUE THREAD

**Issue by piontkowski** [toastedlime/wp-attachment-importer#4]
Deleting all attachments and running program again may cause different files to fail.

**Comment by johu2** [comment]
Are you sure it is not the remote server overloading issue? Does it also
happen with 5 sec delay?

BTW I did not try, but I hope the 5 sec delay is only there, if file does
not exist jet.

**Comment by piontkowski** [comment]
I'm not sure. It could be remote server overloading. Last week I ran 
this program importing 2000 attachments, and I used the 5 second delay, 
and did not get one "Remote server" error. I'm thinking of introducing 
some delay by default.

**Comment by johu2** [comment]
I would not have it by default as it significances increases the time for
long attachment lists. I would keep the manual option and make it easier to
rerun the script with failed elements only (for example produce a XML with
failed elements). In my case I got around 20 failures for 4000 or so
attachments when downloading from wordpress.com. Having 5sec delay would
make the operation really long.

But ofc I understand, that the delay is very easy to implement compered to
'fail filter'. It would be quite easy to iterate the failed elements once
more right away.
