### ISSUE TITLE
No dice for multisite

### ISSUE THREAD

**Issue by paullarrow** [toastedlime/wp-attachment-importer#6]
Thanks for the hard work on this plugin, looks like a good start :) Gave this a whirl on blog id #2 on a multisite install and got hung up at "Importing the attachements…" Would be really excited if you were going to support multisite, although no claims have been made!

-Paul

**Comment by piontkowski** [comment]
Hello, thanks for your comment! Even though I made no claim in the readme, the plugin is tested and works on the latest Multisite, 3.8.1 as of this writing. What version of multisite are you using? What browser and version are you using?

The plugin currently displays no information about the upload, like download or total file progress. Those are planned enhancements. How big is the first file you were trying to import? If it's a big file, the program will appear to hang on Importing the attachments but it is downloading.

**Comment by paullarrow** [comment]
Using a fresh install of 3.8.1. Followed the instructions in the readme:
1. Imported my WXR file using the WordPress importer, but did not select the option to Download and Import Attachments.
2. Navigate to the Attachment Importer screen.
3. Select my WXR export file.
4. Selected current user.
5. Sit back and let the importer run. For a long time. Nadda :(

WXR contained a single post and to clarify, this single post has a Feature Image attached to it (postmeta: _thumbnail). So maybe it works for post content images, but I was hoping it would pull down and re-attach the Featured Image. Holler at me if you have thoughts on that.

-Paul

**Comment by piontkowski** [comment]
Strange, because it works for me following those steps importing a post with a featured image. What browser are you using?

**Comment by piontkowski** [comment]
No response; closing issue.
